name: Deploy React App to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Debug SSH Key content (safe)
      run: echo "$SSH_KEY" | head -n 5
      env:
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    - name: Test SSH connection
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo ✅ Connected to server!"
      env:
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "build"
        target: "/var/www/Shirma"
        strip_components: 1
        rm: true
        overwrite: true
